version: '2'
services:
  rss-bridge:
    image: rssbridge/rss-bridge:latest
    volumes:
      - ./config:/config
      - ./actions:/app/actions
      - ./lib:/app/lib
      - ./formats:/app/formats
      - ./static:/app/static
      - ./templates:/app/templates
      - ./caches:/app/caches
      - ./bridges:/app/bridges
    ports:
      - 3000:80
    restart: unless-stopped
